$(function(){
	$(".hplace").click(function(){
		$(".hroadck").show(500);
		$(".hmsmark").show();
	});
	$(".closehroad").click(function(){
		$(".hroadck").hide(500);
		$(".hmsmark").hide();
	});
	$(".okhroad").click(function(){
		$(".hroadck").hide(500);
		$(".hmsmark").hide();
	});
	$(".moreroad").click(function(){
		$(".hroadck").show(500);
		$(".hmsmark").show();
	});
});